spring:
  datasource:
    url: "jdbc:postgresql://pg-service:5432/billing-payment-service"
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
  cloud:   # notification ile async iletişim
    stream:
      defaultBinder: kafka
      function:
        definition: billingPaymentFunction
      bindings:
        billingPaymentFunction-out-0:
          destination: billing-payment-topic
          content-type: application/json
      kafka:
        binder: 
          brokers: kafka-service:9092
          
server:
  port: 8085

eureka:
  client:
    service-url:
      defaultZone: "http://eureka-service:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
