spring:
  datasource:
    url: jdbc:postgresql://pg-contract-service:5432/contract-service
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: kafka:9092
  cloud:
    stream:
      defaultBinder: kafka
      kafka:
        binder:
          brokers: kafka:9092  # Kafka container adı doğruysa bu yeterli  

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8888/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: contract-service
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
