server:
  port: 8086

spring:
  application:
    name: customer-support-service
  datasource:
    url: jdbc:postgresql://postgres-service:5432/customer-support
    username: postgres
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8888/eureka/"
  instance:
    prefer-ip-address: true

t2:
  security:
    jwt:
      secret: ${JWT_SECRET:your-256-bit-secret}
      expiration: 86400000 # 24 saat
    cors:
      allowed-origins: http://localhost:3000,http://localhost:8080
      allowed-methods: GET,POST,PUT,DELETE,PATCH,OPTIONS
      allowed-headers: Authorization,Content-Type,X-Requested-With
      exposed-headers: Authorization
      allow-credentials: true
      max-age: 3600 
