spring:
  cloud:
    function:
      definition: billingPaymentFunction;userCreatedEventConsumer
    stream:
      defaultBinder: kafka
      bindings:
        billingPaymentFunction-in-0:
          destination: billing-payment-topic
          content-type: application/json
          group: notification-group
        userCreatedEventConsumer-in-0:
          destination: user-created-topic
          content-type: application/json
          group: notification-group
          consumer:
            configuration:
              spring.json.trusted.packages: io.github.ergulberke.event.user
            auto-offset-reset: earliest
      kafka:
        binder:
          brokers: kafka:9092

  data:
    mongodb:
      uri: mongodb://root:root@mongo:27017/notification-service?authSource=admin


server:
  port: 8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka/
    register-with-eureka: true
    fetch-registry: true
