spring:
  datasource:
    url: "jdbc:postgresql://pg-service:5434/postgres"
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
  cloud:   # notification ile async iletişim
    stream:
      defaultBinder: kafka
      function:
        definition: planCreated;planUpdated;planDeleted
      bindings:
        planCreated-out-0:
          destination: plan-created-topic
          content-type: application/json
        planUpdated-out-0:
          destination: plan-updated-topic
          content-type: application/json
        planDeleted-out-0:
          destination: plan-deleted-topic
          content-type: application/json
      kafka:
        binder: 
          brokers: kafka-service:9092
          
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: "http://eureka-service:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
