spring:
  datasource:
    url: "jdbc:postgresql://pg-3:5434/postgres"
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    hibernate:
      ddlAuto: update
  cloud:   
    stream:
      defaultBinder: kafka
      function:
        definition: planCreated;planUpdated;planDeleted
      bindings:
        planCreated-out-0:
          destination: plan-created-topic
          content-type: application/json
        planUpdated-out-0:
          destination: plan-updated-topic
          content-type: application/json
        planDeleted-out-0:
          destination: plan-deleted-topic
          content-type: application/json
      kafka:
        binder: 
          brokers: localhost:9092
          
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8888/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${server.port}
    hostname: config-server
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30

contract:
  service:
    url: http://contract-service:8083
customer:
  service:
    url: http://customer-service:8082
