server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://pg-user-service:5432/userservice
    username: produser
    password: prodpass

  kafka:
    bootstrap-servers: kafka-prod:9092

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
