server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/userservice
    username: postgres
    password: test

  kafka:
    bootstrap-servers: kafka:9092

logging:
  level:
    root: INFO

eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
