server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://user-db-dev:5432/userservice
    username: devuser
    password: devpass

  kafka:
    bootstrap-servers: kafka-dev:9092

eureka:
  client:
    service-url:
      defaultZone: "http://discovery-server:8888/eureka/"
    register-with-eureka: true
    fetch-registry: true
